import { loadDictionary } from "./dictionary.js";
import { getLocale, setLocale } from "./locale";

let currentOutputDir = "./intl";

export function setOutputDir(outputDir: string) {
  currentOutputDir = outputDir;
}

export function getOutputDir() {
  return currentOutputDir;
}

export function translate(
  scope: string,
  locale?: string,
  outputDir?: string
): string {
  const targetLocale = locale || getLocale();
  console.log("targetLocale", targetLocale);
  const targetOutputDir = outputDir || currentOutputDir;

  const dict = loadDictionary(targetLocale, targetOutputDir);
  return dict[scope] || scope;
}

// Convenience function for translating with current settings
export function t(scope: string): string {
  return translate(scope);
}

// Function to translate with file path and scope path (as generated by your parser)
export function translateScope(
  filePath: string,
  scopePath: string,
  locale?: string,
  outputDir?: string
): string {
  const fullScope = `${filePath}::${scopePath}`;
  return translate(fullScope, locale, outputDir);
}

// Function to configure both locale and output directory at once
export function configure(options: { locale?: string; outputDir?: string }) {
  if (options.locale) setLocale(options.locale);
  if (options.outputDir) setOutputDir(options.outputDir);
}

// Function to get translation with fallback
export function translateWithFallback(
  scope: string,
  fallback: string,
  locale?: string,
  outputDir?: string
): string {
  const result = translate(scope, locale, outputDir);
  console.log("result", result);
  return result === scope ? fallback : result;
}
